[2021-12-12 20:15:42,626] [INFO] [base._load_session] -> No session loaded
[2021-12-12 20:15:42,628] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 127.0.0.1:26001
                 Log: ./kittylogs/kitty_20211212-201539.log

                 Total possible mutation count: 0
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2021-12-12 20:15:42,628] [INFO] [base.start] -> Performing environment test
[2021-12-12 20:15:42,630] [INFO] [base._test_info] -> Current test: -1
[2021-12-12 20:15:42,630] [INFO] [server.transmit] -> request(81): 62275c7830335c7830305c7830305c7831615c7831355c7865305c7830305c7830305c7830305c7830315c7830305c786330 ...
[2021-12-12 20:15:44,634] [ERROR] [server.transmit] -> target.transmit - failure in receive (exception: timed out)
[2021-12-12 20:15:44,636] [ERROR] [server.transmit] -> Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\targets\server.py", line 98, in transmit
    response = self._receive_from_target()
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\katnip\targets\tcp.py", line 86, in _receive_from_target
    return self.socket.recv(10000)
socket.timeout: timed out

[2021-12-12 20:15:44,638] [WARNING] [base.post_test] -> Test -1 status: failed
[2021-12-12 20:15:44,638] [WARNING] [base.post_test] -> Reason: failed to receive response: timed out
[2021-12-12 20:15:44,639] [INFO] [server._test_environment] -> Environment test failed
[2021-12-12 20:15:44,639] [ERROR] [base.start] -> Error occurred while fuzzing: Exception('Environment test failed')
[2021-12-12 20:15:44,640] [ERROR] [base.start] -> Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\fuzzers\base.py", line 385, in start
    self._test_environment()
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\fuzzers\server.py", line 54, in _test_environment
    raise Exception('Environment test failed')
Exception: Environment test failed

