[2022-01-06 16:41:18,316] [INFO] [base._load_session] -> No session loaded
[2022-01-06 16:41:18,319] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: FileTarget
                 UI: WebInterface listening on 127.0.0.1:26001
                 Log: ./kittylogs/kitty_20220106-164117.log

                 Total possible mutation count: 91
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2022-01-06 16:41:18,325] [INFO] [base.start] -> Performing environment test
[2022-01-06 16:41:18,329] [INFO] [base._test_info] -> Current test: -1
[2022-01-06 16:41:18,330] [INFO] [server.transmit] -> request(18): 5468652064656661756c7420737472696e67
[2022-01-06 16:41:18,338] [INFO] [server._test_environment] -> Environment test failed
[2022-01-06 16:41:18,338] [ERROR] [base.start] -> Error occurred while fuzzing: Exception('status must be one of: passed, failed, error')
[2022-01-06 16:41:18,340] [ERROR] [base.start] -> Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\fuzzers\base.py", line 385, in start
    self._test_environment()
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\fuzzers\server.py", line 54, in _test_environment
    if self._run_sequence(sequence):
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\fuzzers\server.py", line 76, in _run_sequence
    return self._post_test()
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\fuzzers\base.py", line 435, in _post_test
    self.target.post_test(self.model.current_index())
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\targets\server.py", line 129, in post_test
    super(ServerTarget, self).post_test(test_num)
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\targets\base.py", line 97, in post_test
    controller_report = self.controller.get_report()
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\remote\actor.py", line 41, in get_report
    report = Report.from_dict(report_dict)
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\data\report.py", line 205, in from_dict
    report.set_status(Report._decode(d['status'], encoding))
  File "D:\windowsSoftware\Anaconda\envs\miio\lib\site-packages\kitty\data\report.py", line 128, in set_status
    raise Exception('status must be one of: %s' % (', '.join(Report.allowed_statuses)))
Exception: status must be one of: passed, failed, error

