[2021-09-13 16:47:01,194] [INFO] [base._load_session] -> No session loaded
[2021-09-13 16:47:01,196] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 127.0.0.1:26011
                 Log: ./kittylogs/kitty_20210913-164700.log

                 Total possible mutation count: 361
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2021-09-13 16:47:01,198] [INFO] [base.start] -> Performing environment test
[2021-09-13 16:47:01,202] [INFO] [base._test_info] -> Current test: -1
[2021-09-13 16:47:01,202] [INFO] [server.transmit] -> request(28): 474554202f696e6465782e68746d6c20485454502f312e310d0a0d0a
[2021-09-13 16:47:01,203] [ERROR] [server.transmit] -> target.transmit - failure in send (exception: 'socket' object has no attribute 'sned')
[2021-09-13 16:47:01,203] [ERROR] [server.transmit] -> Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\targets\server.py", line 93, in transmit
    self._send_to_target(payload)
  File "d:\CodeHub\Kitty\example\model\fuzzing\fuzzing.py", line 80, in _send_to_target
    self.socket.sned(data)
AttributeError: 'socket' object has no attribute 'sned'

[2021-09-13 16:47:01,204] [WARNING] [base.post_test] -> Test -1 status: failed
[2021-09-13 16:47:01,205] [WARNING] [base.post_test] -> Reason: failed to send payload: 'socket' object has no attribute 'sned'
[2021-09-13 16:47:01,205] [INFO] [server._test_environment] -> Environment test failed
[2021-09-13 16:47:01,206] [ERROR] [base.start] -> Error occurred while fuzzing: Exception('Environment test failed')
[2021-09-13 16:47:01,206] [ERROR] [base.start] -> Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\fuzzers\base.py", line 385, in start
    self._test_environment()
  File "D:\windowsSoftware\Anaconda\envs\Kitty\lib\site-packages\kitty\fuzzers\server.py", line 54, in _test_environment
    raise Exception('Environment test failed')
Exception: Environment test failed

